# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Body')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('addresee', models.CharField(blank=True, max_length=255, null=True, verbose_name='Addresee')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
